### ISSUE TITLE
QUIC check stopped working

### ISSUE THREAD

**Issue by fgrueninger** [3bl3gamer/storjnet-info#17]
Hi,

the QUIC check seems to be broken, I'm always getting this:

`QUIC: couldn't connect to node: rpc: quic: context deadline exceeded`

Could you please check? Thanks a lot!

**Comment by 3bl3gamer** [comment]
Hi, do you mean https://storjnet.info/ping_my_node ? It works for my two nodes with different locations.

I've added some logging, so could you please run the check one more time and provide part of your node ID? Or even whole ID if you don't mind that it's hanging around on the Internet :)

**Comment by fgrueninger** [comment]
Yes, I just tried with the node starting with 1U7A, you think it's an issue of my node? Thanks!

**Comment by 3bl3gamer** [comment]
Ok, I've manually checked your node from different locations. TCP works all the time, and QUIC ends with timeout, but only from Russian IPs (it worked from Italy and France). Not sure what is the cause: maybe it's the Russian Internet restrictions, maybe some king of anti-DDoS protection (which for some reason blocks only Russian UDP). But I'm 99%-sure that it's not and issue of *your node*.

Anyway, looks like I'll have to add QUIC to the proxy mode.

In case of anti-DDoS, there is a small chance that changing the node's port to different (and uncommon) one may help. It's not very important, but if you decide to check, please write about the results, it's interesting :)

**Comment by fgrueninger** [comment]
I started another node on port 28967 temporarily, and the QUIC check worked from Russia, too.
Most probably it's your ISP and not your code, so we may close this issue ;) Thanks again!
